const productos = [
  {
    id: 1,
    name: 'Producto 1',
    descripcion: 'Descripcion del producto 1',
    categoria: 1,
    precio: 1.0,
    img: 'https://dummyimage.com/300/0000ff',
  },
  {
    id: 2,
    name: 'Producto 2',
    descripcion: 'Descripcion del producto 2',
    categoria: 2,
    precio: 2.0,
    img: 'https://dummyimage.com/300/00ff00',
  },
  {
    id: 3,
    name: 'Producto 3',
    descripcion: 'Descripcion del producto 3',
    categoria: 3,
    precio: 5.0,
    img: 'https://dummyimage.com/300/ff0000',
  },
  {
    id: 4,
    name: 'Producto 4',
    descripcion: 'Descripcion del producto 4',
    categoria: 1,
    precio: 10.0,
    img: 'https://dummyimage.com/300/00ff00',
  },
  {
    id: 5,
    name: 'Producto 5',
    descripcion: 'Descripcion del producto 5',
    categoria: 2,
    precio: 20.0,
    img: 'https://dummyimage.com/300/ff0000',
  },
  {
    id: 6,
    name: 'Producto 6',
    descripcion: 'Descripcion del producto 6',
    categoria: 3,
    precio: 50.0,
    img: 'https://dummyimage.com/300/0000ff',
  },
  {
    id: 7,
    name: 'Producto 7',
    descripcion: 'Descripcion del producto 7',
    categoria: 1,
    precio: 100.0,
    img: 'https://dummyimage.com/300/ff0000',
  },
  {
    id: 8,
    name: 'Producto 8',
    descripcion: 'Descripcion del producto 8',
    categoria: 2,
    precio: 200.0,
    img: 'https://dummyimage.com/300/0000ff',
  },
  {
    id: 9,
    name: 'Producto 9',
    descripcion: 'Descripcion del producto 9',
    categoria: 3,
    precio: 500.0,
    img: 'https://dummyimage.com/300/00ff00',
  },
];
